### ISSUE TITLE
Create 

### ISSUE THREAD

**Issue by marcus-goncalves** [marcus-goncalves/workana-sales-management#7]

**Comment by marcus-goncalves** [comment]
### User map story
- As a seller, i want to register myself so I can use the system

### Pre-requisites
- [ ] Should create a user
- [ ] Should login a user
- [ ] Should reset password
- [ ] Should validate password
- [ ] Should not allow more than 1 user per email
- [ ] Should allow to update user data
- [ ] Should maintain a session for the user

### Tasks
- [ ] Create a user schema
- [ ] CRUD for user
- [ ] Encrypt password when creating user
- [ ] Create Authentication logic
